[libraries]
koios-java = "io.github.cardano-community:koios-java-client:1.18.0"
ogmios-java = "io.adabox:ogmios-java-client:1.0.0"

slf4j-api = "org.slf4j:slf4j-api:1.7.36"
slf4j-log4j = "org.slf4j:slf4j-log4j12:1.7.36"

bouncycastle-bcprov = "org.bouncycastle:bcprov-jdk15to18:1.71"
guava = "com.google.guava:guava:32.1.2-jre"
co-nstant-in-cbor = "co.nstant.in:cbor:0.9"
i2p-crypto-eddsa = "net.i2p.crypto:eddsa:0.3.0"

jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.15.0"
retrofit2 = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit2-converter-jackson = "com.squareup.retrofit2:converter-jackson:2.9.0"
okhttp = "com.squareup.okhttp3:okhttp:4.10.0"

yaci = "com.bloxbean.cardano:yaci:0.2.4"
aiken-java-binding = "com.bloxbean.cardano:aiken-java-binding:0.0.8"

google-auto-service="com.google.auto.service:auto-service:1.1.1"
javapoet="com.squareup:javapoet:1.13.0"
google-testing-compile="com.google.testing.compile:compile-testing:0.21.0"

lombok = "org.projectlombok:lombok:1.18.28"
